set(_CATKIN_CURRENT_PACKAGE "move_basic")
set(move_basic_VERSION "0.3.2")
set(move_basic_MAINTAINER "Jim Vaughan <jimv@mrjim.com>, Rohan Agrawal <send2arohan@gmail.com>")
set(move_basic_PACKAGE_FORMAT "2")
set(move_basic_BUILD_DEPENDS "roscpp" "tf2_geometry_msgs" "tf2_ros" "tf2" "geometry_msgs" "sensor_msgs" "visualization_msgs" "std_msgs" "nav_core" "actionlib" "actionlib_msgs" "move_base_msgs")
set(move_basic_BUILD_EXPORT_DEPENDS "roscpp" "tf2_geometry_msgs" "tf2_ros" "tf2" "geometry_msgs" "sensor_msgs" "visualization_msgs" "std_msgs" "nav_core" "actionlib" "actionlib_msgs" "move_base_msgs")
set(move_basic_BUILDTOOL_DEPENDS "catkin")
set(move_basic_BUILDTOOL_EXPORT_DEPENDS )
set(move_basic_EXEC_DEPENDS "roscpp" "tf2_geometry_msgs" "tf2_ros" "tf2" "geometry_msgs" "sensor_msgs" "visualization_msgs" "std_msgs" "nav_core" "actionlib" "actionlib_msgs" "move_base_msgs")
set(move_basic_RUN_DEPENDS "roscpp" "tf2_geometry_msgs" "tf2_ros" "tf2" "geometry_msgs" "sensor_msgs" "visualization_msgs" "std_msgs" "nav_core" "actionlib" "actionlib_msgs" "move_base_msgs")
set(move_basic_TEST_DEPENDS )
set(move_basic_DOC_DEPENDS )
set(move_basic_URL_WEBSITE "")
set(move_basic_URL_BUGTRACKER "")
set(move_basic_URL_REPOSITORY "")
set(move_basic_DEPRECATED "")