# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from move_basic/FollowMode.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class FollowMode(genpy.Message):
  _md5sum = "ca3124bca40836e775d2e61109ec4829"
  _type = "move_basic/FollowMode"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Message to request different follow behavior
uint8 DRIVE_STRAIGHT=0
uint8 FOLLOW_LEFT=1
uint8 FOLLOW_RIGHT=2

uint8 follow_mode
float32 follow_dist
float32 speed
"""
  # Pseudo-constants
  DRIVE_STRAIGHT = 0
  FOLLOW_LEFT = 1
  FOLLOW_RIGHT = 2

  __slots__ = ['follow_mode','follow_dist','speed']
  _slot_types = ['uint8','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       follow_mode,follow_dist,speed

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FollowMode, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.follow_mode is None:
        self.follow_mode = 0
      if self.follow_dist is None:
        self.follow_dist = 0.
      if self.speed is None:
        self.speed = 0.
    else:
      self.follow_mode = 0
      self.follow_dist = 0.
      self.speed = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B2f().pack(_x.follow_mode, _x.follow_dist, _x.speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.follow_mode, _x.follow_dist, _x.speed,) = _get_struct_B2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B2f().pack(_x.follow_mode, _x.follow_dist, _x.speed))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.follow_mode, _x.follow_dist, _x.speed,) = _get_struct_B2f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B2f = None
def _get_struct_B2f():
    global _struct_B2f
    if _struct_B2f is None:
        _struct_B2f = struct.Struct("<B2f")
    return _struct_B2f
